### ISSUE TITLE
Connect does not make connection

### ISSUE THREAD

**Issue by erniecox** [chrisbutler/tls#3]
From the sample code when I attempt a connection no IP traffic is generated to the specified host and endpoint.

//connect to TLS-350 and output getTanks to console
var myTLS = new TLS.connect('192.168.56.25', 10001);
console.log(myTLS.getTanks());

**Comment by chrisbutler** [comment]
@erniecox is there any console output in your terminal?

**Comment by erniecox** [comment]
Ah it appears it "cannot find module" my import is
import { TLS } from 'meteor/chrisbutler_tls';  

incorrect syntax??

**Comment by chrisbutler** [comment]
you should be able to leave out that entire line. this package was written before meteor had es2015 module support, so the `import` syntax won't work with it. `TLS` should be in the global namespace
